# Generated by Django 2.0 on 2019-06-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FakeData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('job', models.CharField(max_length=30)),
                ('salary', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
            ],
        ),
    ]
